### ISSUE TITLE
渡されたデータをデータベースに保存する関数とidを渡されると構造体を返す関数を作成

### ISSUE THREAD

**Issue by Orion042** [swkoubou/HackU2021#9]
- [x] mysqlへの接続 (ローカルでの実験)
- [x] 簡易的な関数を作成し，idを渡されるとデータベースに保存してあるデータを構造体として返す
- [x] 簡易的な関数を作成し，構造体を渡されるとデータベースにデータが追加できる
- [ ] 本番で使用する構造体を定義する
- [ ] 分割ファイルとして正しく機能することの確認

closed #9

**Comment by okapon1210** [comment]
分割したのでこっちは閉じます
